// src/lib/mock-data.ts
// Mock data for development and demonstration
// Replace with real database calls when backend is configured

import type { ScanReport, DashboardStats, BatchJob, ApiKey, ApiActivity, AuditLog, TeamMember, Workspace } from '@/types';

export const mockScans: ScanReport[] = [
  {
    id: 'scan_001',
    scanId: 'scan_001',
    contentName: 'quarterly-report-draft.pdf',
    contentType: 'text',
    status: 'completed',
    result: 'ai_generated',
    overallScore: 82,
    confidenceScore: 82,
    evidenceStrength: 'strong',
    modules: ['ai_generation'],
    modelVersion: '1.0.0',
    limitations: [
      'Results are probabilistic and may contain errors',
      'Heavily edited AI text may score lower than expected',
      'Short sections analyzed in isolation may be less accurate',
    ],
    recommendations: [
      'Review the document with the original author',
      'Request revision history or writing drafts',
      'Perform an independent analysis with another tool',
    ],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 2 * 60 * 60 * 1000 + 8000).toISOString(),
    textSignals: [
      { name: 'High Sentence Uniformity', description: 'Sentence lengths show very low variation, typical of AI generation', score: 0.85, confidence: 0.88, passages: [] },
      { name: 'AI Transition Phrases', description: "Phrases like 'Furthermore', 'Moreover', 'In conclusion' appear frequently", score: 0.79, confidence: 0.82, passages: [] },
      { name: 'Low Perplexity Score', description: 'Text follows highly predictable statistical word patterns', score: 0.80, confidence: 0.85, passages: [] },
      { name: 'Formal Register Consistency', description: 'Writing register remains unnaturally consistent throughout', score: 0.70, confidence: 0.75, passages: [] },
    ],
    fileHash: 'sha256:a3f8c2e1d4b7f6a9c2e5d8b1f4a7c0e3d6b9f2a5',
    tags: ['pdf', 'report', 'business'],
  },
  {
    id: 'scan_002',
    scanId: 'scan_002',
    contentName: 'product-photo-hero.jpg',
    contentType: 'image',
    status: 'completed',
    result: 'ai_enhanced',
    overallScore: 65,
    confidenceScore: 65,
    evidenceStrength: 'moderate',
    modules: ['ai_generation', 'enhancement'],
    modelVersion: '1.0.0',
    limitations: [
      'Image compression may reduce detection accuracy',
      'Some enhancement techniques are difficult to distinguish from natural processing',
    ],
    recommendations: [
      'Request the original unedited RAW or TIFF file',
      'Compare with previous versions of the image',
      'Check publication and editing history',
    ],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 5 * 60 * 60 * 1000 + 4000).toISOString(),
    imageSignals: [
      { name: 'Possible AI Upscaling', description: 'Pixel-level patterns suggest super-resolution upscaling', score: 0.72, confidence: 0.68, regions: [] },
      { name: 'Artificial Sharpening', description: 'Edge enhancement inconsistencies detected', score: 0.58, confidence: 0.62, regions: [] },
    ],
    fileHash: 'sha256:b4c9d3f7e2a6b8d1f5c3e7a2b9d4f8c1e6a3b7',
    tags: ['image', 'product'],
  },
  {
    id: 'scan_003',
    scanId: 'scan_003',
    contentName: 'personal-essay.txt',
    contentType: 'text',
    status: 'completed',
    result: 'human',
    overallScore: 18,
    confidenceScore: 74,
    evidenceStrength: 'moderate',
    modules: ['ai_generation'],
    modelVersion: '1.0.0',
    limitations: [
      'Human writing with consistent style may occasionally score higher',
      'Academic or formal writing may resemble AI-generated content',
    ],
    recommendations: [
      'No further action recommended based on current analysis',
      'Consider an independent review if results are important',
    ],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 24 * 60 * 60 * 1000 + 5000).toISOString(),
    textSignals: [
      { name: 'Natural Sentence Variation', description: 'Sentence lengths vary naturally, consistent with human writing', score: 0.15, confidence: 0.78 },
      { name: 'Personal Voice Detected', description: 'First-person perspective and unique phrasing detected', score: 0.10, confidence: 0.72 },
    ],
    fileHash: 'sha256:c5e0f4g8h3i7j2k6l1m5n9o4p8q3r7s2t6u1v5',
    tags: ['text', 'essay'],
  },
  {
    id: 'scan_004',
    scanId: 'scan_004',
    contentName: 'news-interview.mp4',
    contentType: 'video',
    status: 'completed',
    result: 'inconclusive',
    overallScore: 48,
    confidenceScore: 42,
    evidenceStrength: 'weak',
    modules: ['ai_generation', 'deepfake', 'enhancement'],
    modelVersion: '1.0.0',
    limitations: [
      'Video compression significantly reduces detection accuracy',
      'Social media encoding may obscure synthetic artifacts',
      'Short video clips provide limited evidence',
    ],
    recommendations: [
      'Request the original uncompressed video file',
      'Perform analysis on a higher-quality copy',
      'Consult digital forensics professionals for critical decisions',
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 25000).toISOString(),
    fileHash: 'sha256:d6f1g5h9i4j8k3l7m2n6o1p5q9r4s8t3u7v2w6',
    tags: ['video', 'news'],
  },
  {
    id: 'scan_005',
    scanId: 'scan_005',
    contentName: 'social-media-post.jpg',
    contentType: 'image',
    status: 'completed',
    result: 'ai_generated',
    overallScore: 91,
    confidenceScore: 91,
    evidenceStrength: 'strong',
    modules: ['ai_generation'],
    modelVersion: '1.0.0',
    limitations: [
      'Results are probabilistic',
      'Some high-quality AI images may be difficult to detect after processing',
    ],
    recommendations: [
      'Contact the content creator for source files',
      'Check content credentials (C2PA) if available',
      'Request the original camera file or generation prompt',
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 3000).toISOString(),
    imageSignals: [
      { name: 'GAN Fingerprint Detected', description: 'Pixel noise patterns consistent with generative model output', score: 0.93, confidence: 0.91, regions: [] },
      { name: 'Texture Inconsistencies', description: 'Abnormal texture patterns in background elements', score: 0.88, confidence: 0.89, regions: [] },
      { name: 'Facial Irregularities', description: 'Subtle facial geometry inconsistencies detected', score: 0.85, confidence: 0.87, regions: [] },
    ],
    fileHash: 'sha256:e7g2h6i0j5k9l4m8n3o7p2q6r1s5t9u4v8w3x7',
    tags: ['image', 'social-media'],
  },
];

export const mockDashboardStats: DashboardStats = {
  totalScans: 47,
  textScans: 22,
  imageScans: 18,
  videoScans: 7,
  likelyAiGenerated: 19,
  likelyHuman: 15,
  enhanced: 8,
  inconclusive: 5,
  scansOverTime: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.now() - (29 - i) * 24 * 60 * 60 * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    scans: Math.floor(Math.random() * 5) + 0,
  })),
  contentTypeDistribution: [
    { type: 'Text', count: 22 },
    { type: 'Image', count: 18 },
    { type: 'Video', count: 7 },
  ],
  resultDistribution: [
    { result: 'AI-Generated', count: 19 },
    { result: 'Human-Created', count: 15 },
    { result: 'AI-Enhanced', count: 8 },
    { result: 'Inconclusive', count: 5 },
  ],
  avgConfidenceByType: [
    { type: 'Text', confidence: 74 },
    { type: 'Image', confidence: 68 },
    { type: 'Video', confidence: 52 },
  ],
};

export const mockBatchJobs: BatchJob[] = [
  {
    id: 'batch_001',
    userId: 'user_001',
    name: 'Marketing Assets Review',
    status: 'completed',
    items: [],
    totalItems: 15,
    completedItems: 15,
    failedItems: 0,
    modules: ['ai_generation', 'enhancement'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 300000).toISOString(),
  },
  {
    id: 'batch_002',
    userId: 'user_001',
    name: 'News Article Fact-Check',
    status: 'processing',
    items: [],
    totalItems: 8,
    completedItems: 5,
    failedItems: 1,
    modules: ['ai_generation', 'deepfake', 'metadata'],
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export const mockApiKeys: ApiKey[] = [
  {
    id: 'key_001',
    name: 'Production API',
    keyPrefix: 'osk_prod_',
    lastUsedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    requestCount: 1247,
    rateLimit: 100,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
  },
  {
    id: 'key_002',
    name: 'Development Testing',
    keyPrefix: 'osk_dev_',
    lastUsedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    requestCount: 348,
    rateLimit: 100,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
  },
  {
    id: 'key_003',
    name: 'Old Integration',
    keyPrefix: 'osk_old_',
    requestCount: 50,
    rateLimit: 100,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    revokedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: false,
  },
];

export const mockWorkspace: Workspace = {
  id: 'ws_001',
  name: 'Newsroom Team',
  slug: 'newsroom-team',
  ownerId: 'user_001',
  members: [
    {
      id: 'mem_001',
      userId: 'user_001',
      email: 'alex@example.com',
      name: 'Alex Johnson',
      role: 'owner',
      joinedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      lastActiveAt: new Date().toISOString(),
    },
    {
      id: 'mem_002',
      userId: 'user_002',
      email: 'sam@example.com',
      name: 'Sam Rivera',
      role: 'analyst',
      joinedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      lastActiveAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'mem_003',
      userId: 'user_003',
      email: 'jordan@example.com',
      name: 'Jordan Lee',
      role: 'reviewer',
      joinedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      lastActiveAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'mem_004',
      userId: 'user_004',
      email: 'morgan@example.com',
      name: 'Morgan Chen',
      role: 'viewer',
      joinedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  memberLimit: 25,
  createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
};

export const mockAuditLogs: AuditLog[] = [
  { id: '1', userId: 'user_001', userName: 'Alex Johnson', action: 'scan.created', resource: 'Scan', resourceId: 'scan_001', createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
  { id: '2', userId: 'user_002', userName: 'Sam Rivera', action: 'report.shared', resource: 'Report', resourceId: 'scan_002', createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  { id: '3', userId: 'user_001', userName: 'Alex Johnson', action: 'api_key.created', resource: 'ApiKey', resourceId: 'key_001', createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
  { id: '4', userId: 'user_003', userName: 'Jordan Lee', action: 'scan.viewed', resource: 'Scan', resourceId: 'scan_003', createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString() },
  { id: '5', userId: 'user_001', userName: 'Alex Johnson', action: 'member.invited', resource: 'Workspace', resourceId: 'ws_001', metadata: { invitedEmail: 'morgan@example.com' }, createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
];
