'use client';
import { useState, useRef } from 'react';
import { motion, useInView, AnimatePresence } from 'framer-motion';
import { Plus, Minus, HelpCircle } from 'lucide-react';

const faqs = [
  {
    q: 'Is AI Shield really free?',
    a: 'Yes, AI Shield is completely free to use. We do not have premium tiers, paywalls, or subscription fees. Our mission is to democratize access to AI detection tools. We rely on fair-use limits to prevent abuse.',
  },
  {
    q: 'How accurate is the detection?',
    a: 'Our models are highly accurate on standard benchmarks, but no tool is 100% accurate in real-world scenarios. We provide a probability score indicating the likelihood of AI generation. False positives and false negatives can occur.',
  },
  {
    q: 'Do you store the files I upload?',
    a: 'We process files securely for analysis. For registered users, we may temporarily store files to generate reports, but you can delete them at any time. We do not use user uploads to train generative AI models.',
  },
  {
    q: 'Can it detect ChatGPT 4 or Claude 3 text?',
    a: 'Yes, our text detection models are continuously updated to identify patterns from the latest Large Language Models, including GPT-4, Claude 3, and Gemini.',
  },
  {
    q: 'What types of images can it analyze?',
    a: 'We support standard image formats (JPEG, PNG, WebP) and can detect content generated by tools like Midjourney, DALL-E 3, Stable Diffusion, as well as AI-edited photos (e.g., Photoshop Generative Fill).',
  },
  {
    q: 'Can I use this for academic grading?',
    a: 'We strongly advise against using any AI detection tool as the sole basis for punitive academic decisions. It should only be used as a supplementary tool alongside human review and discussion with the student.',
  },
  {
    q: 'What is deepfake detection?',
    a: 'Our deepfake detection analyzes videos for synthetic manipulation, such as face swapping or AI lip-syncing. It looks for spatial and temporal anomalies that humans might miss.',
  },
  {
    q: 'Do you have an API?',
    a: 'Yes, we offer a free API for developers to integrate AI Shield into their own applications. Check our API documentation for details and rate limits.',
  },
];

function FAQItem({ faq, index }: { faq: { q: string; a: string }; index: number }) {
  const [open, setOpen] = useState(false);

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: index * 0.07 }}
      className="group"
    >
      <div
        className={`rounded-xl border transition-all duration-300 overflow-hidden ${
          open
            ? 'border-cyan-azure/40 bg-space-cadet-light/30'
            : 'border-cyan-azure/15 bg-space-cadet-dark/60 hover:border-cyan-azure/30'
        }`}
      >
        <button
          onClick={() => setOpen(!open)}
          className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left"
          aria-expanded={open}
        >
          <span className={`font-medium text-sm md:text-base transition-colors ${open ? 'text-foreground' : 'text-foreground/80 group-hover:text-foreground'}`}>
            {faq.q}
          </span>
          <span className={`shrink-0 w-7 h-7 rounded-full flex items-center justify-center transition-all duration-300 ${
            open ? 'bg-cyan-azure/20 text-cyan-azure border border-cyan-azure/35' : 'bg-space-cadet-dark border border-cyan-azure/20 text-air-sup-blue'
          }`}>
            {open ? <Minus className="w-3.5 h-3.5" /> : <Plus className="w-3.5 h-3.5" />}
          </span>
        </button>

        <AnimatePresence initial={false}>
          {open && (
            <motion.div
              key="content"
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3, ease: [0.4, 0, 0.2, 1] }}
              className="overflow-hidden"
            >
              <div className="px-6 pb-5 border-t border-cyan-azure/10 pt-4">
                <p className="text-sm text-air-sup-blue leading-relaxed">{faq.a}</p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

export function FAQ() {
  const ref    = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-60px' });

  return (
    <section className="py-28 relative overflow-hidden bg-space-cadet-dark">
      <div className="absolute inset-0 bg-dot-pattern opacity-15 pointer-events-none" />
      <div className="absolute inset-x-0 top-0 h-px" style={{ background: 'linear-gradient(90deg, transparent, rgba(78,122,177,0.3), rgba(206,181,212,0.2), rgba(78,122,177,0.3), transparent)' }} />

      {/* Centre orb */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full pointer-events-none"
        style={{ background: 'radial-gradient(circle, rgba(78,122,177,0.05) 0%, transparent 70%)' }} />

      <div className="container mx-auto px-4 max-w-3xl relative z-10" ref={ref}>
        <motion.div
          className="text-center mb-14"
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.55 }}
        >
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full badge-primary text-xs font-semibold uppercase tracking-widest mb-5">
            <HelpCircle className="w-3 h-3 text-cyan-azure" />
            FAQs
          </span>
          <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-foreground mb-5">
            Frequently Asked{' '}
            <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-air-sup-blue text-lg">Everything you need to know about AI Shield.</p>
        </motion.div>

        <div className="space-y-3">
          {faqs.map((faq, i) => (
            <FAQItem key={i} faq={faq} index={i} />
          ))}
        </div>
      </div>
    </section>
  );
}
