import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

const faqs = [
  {
    q: 'Is AI Shield really free?',
    a: 'Yes, AI Shield is completely free to use. We do not have premium tiers, paywalls, or subscription fees. Our mission is to democratize access to AI detection tools. We rely on fair-use limits to prevent abuse.',
  },
  {
    q: 'How accurate is the detection?',
    a: 'Our models are highly accurate on standard benchmarks, but no tool is 100% accurate in real-world scenarios. We provide a probability score indicating the likelihood of AI generation. False positives and false negatives can occur.',
  },
  {
    q: 'Do you store the files I upload?',
    a: 'We process files securely for analysis. For registered users, we may temporarily store files to generate reports, but you can delete them at any time. We do not use user uploads to train generative AI models.',
  },
  {
    q: 'Can it detect ChatGPT 4 or Claude 3 text?',
    a: 'Yes, our text detection models are continuously updated to identify patterns from the latest Large Language Models, including GPT-4, Claude 3, and Gemini.',
  },
  {
    q: 'What types of images can it analyze?',
    a: 'We support standard image formats (JPEG, PNG, WebP) and can detect content generated by tools like Midjourney, DALL-E 3, Stable Diffusion, as well as AI-edited photos (e.g., Photoshop Generative Fill).',
  },
  {
    q: 'Can I use this for academic grading?',
    a: 'We strongly advise against using any AI detection tool as the sole basis for punitive academic decisions. It should only be used as a supplementary tool alongside human review and discussion with the student.',
  },
  {
    q: 'What is deepfake detection?',
    a: 'Our deepfake detection analyzes videos for synthetic manipulation, such as face swapping or AI lip-syncing. It looks for spatial and temporal anomalies that humans might miss.',
  },
  {
    q: 'Do you have an API?',
    a: 'Yes, we offer a free API for developers to integrate AI Shield into their own applications. Check our API documentation for details and rate limits.',
  },
];

export function FAQ() {
  return (
    <section className="py-24 bg-space-cadet-dark border-t border-cyan-azure/15">
      <div className="container mx-auto px-4 max-w-3xl">
        <div className="text-center mb-12">
          <span className="inline-block px-3 py-1 rounded-full badge-primary text-xs font-semibold uppercase tracking-wider mb-4 text-cyan-azure">
            FAQs
          </span>
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-foreground mb-4">
            Frequently Asked{' '}
            <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-air-sup-blue">Everything you need to know about AI Shield.</p>
        </div>

        <Accordion type="single" collapsible className="w-full space-y-2">
          {faqs.map((faq, index) => (
            <AccordionItem
              key={index}
              value={`item-${index}`}
              className="glass-card rounded-xl border border-cyan-azure/15 px-2 overflow-hidden"
            >
              <AccordionTrigger className="text-left text-foreground hover:text-pink-lavender transition-colors py-4 px-2">
                {faq.q}
              </AccordionTrigger>
              <AccordionContent className="text-air-sup-blue leading-relaxed pb-4 px-2">
                {faq.a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
