import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

const faqs = [
  {
    q: 'Is AI Sheild really free?',
    a: 'Yes, AI Sheild is completely free to use. We do not have premium tiers, paywalls, or subscription fees. Our mission is to democratize access to AI detection tools. We rely on fair-use limits to prevent abuse.'
  },
  {
    q: 'How accurate is the detection?',
    a: 'Our models are highly accurate on standard benchmarks, but no tool is 100% accurate in real-world scenarios. We provide a probability score indicating the likelihood of AI generation. False positives and false negatives can occur.'
  },
  {
    q: 'Do you store the files I upload?',
    a: 'We process files securely for analysis. For registered users, we may temporarily store files to generate reports, but you can delete them at any time. We do not use user uploads to train generative AI models.'
  },
  {
    q: 'Can it detect ChatGPT 4 or Claude 3 text?',
    a: 'Yes, our text detection models are continuously updated to identify patterns from the latest Large Language Models, including GPT-4, Claude 3, and Gemini.'
  },
  {
    q: 'What types of images can it analyze?',
    a: 'We support standard image formats (JPEG, PNG, WebP) and can detect content generated by tools like Midjourney, DALL-E 3, Stable Diffusion, as well as AI-edited photos (e.g., Photoshop Generative Fill).'
  },
  {
    q: 'Can I use this for academic grading?',
    a: 'We strongly advise against using any AI detection tool as the sole basis for punitive academic decisions. It should only be used as a supplementary tool alongside human review and discussion with the student.'
  },
  {
    q: 'What is deepfake detection?',
    a: 'Our deepfake detection analyzes videos for synthetic manipulation, such as face swapping or AI lip-syncing. It looks for spatial and temporal anomalies that humans might miss.'
  },
  {
    q: 'Do you have an API?',
    a: 'Yes, we offer a free API for developers to integrate AI Sheild into their own applications. Check our API documentation for details and rate limits.'
  }
];

export function FAQ() {
  return (
    <section className="py-20 bg-surface border-t border-border">
      <div className="container mx-auto px-4 max-w-3xl">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold tracking-tight text-white mb-4">Frequently Asked Questions</h2>
          <p className="text-muted-foreground">Everything you need to know about AI Sheild.</p>
        </div>

        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <AccordionItem key={index} value={`item-${index}`} className="border-border">
              <AccordionTrigger className="text-left text-foreground hover:text-cyan-400 transition-colors">
                {faq.q}
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground leading-relaxed">
                {faq.a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
