import { FileText, Image as ImageIcon, Video, UserX, Sparkles, Layers, Database, Files } from 'lucide-react';

const features = [
  { title: 'AI Text Detection',         icon: FileText,  desc: 'Identify text generated by ChatGPT, Claude, Gemini, and other LLMs.' },
  { title: 'AI Image Detection',        icon: ImageIcon, desc: 'Detect images created by Midjourney, DALL-E, Stable Diffusion, etc.' },
  { title: 'AI Video Detection',        icon: Video,     desc: 'Spot fully synthetic AI-generated video content.' },
  { title: 'Deepfake Detection',        icon: UserX,     desc: 'Identify face-swaps, lip-sync manipulation, and synthetic voices.' },
  { title: 'Image Enhancement',         icon: Sparkles,  desc: 'Detect AI upscaling, generative fill, and synthetic edits.' },
  { title: 'Video Enhancement',         icon: Layers,    desc: 'Spot AI frame interpolation and resolution enhancement.' },
  { title: 'Metadata Analysis',         icon: Database,  desc: 'Extract and analyze hidden EXIF/metadata for manipulation signs.' },
  { title: 'Batch Analysis',            icon: Files,     desc: 'Scan multiple files or entire documents at once.' },
];

/* Cycle through palette accent colors for icon containers */
const accentCycles = [
  'bg-cyan-azure/15 border-cyan-azure/30 text-cyan-azure',
  'bg-pink-lavender/15 border-pink-lavender/30 text-pink-lavender',
  'bg-air-sup-blue/15 border-air-sup-blue/30 text-air-sup-blue',
  'bg-ucla-blue/30 border-ucla-blue/40 text-air-sup-blue',
];

export function Features() {
  return (
    <section className="py-24 bg-space-cadet-dark relative overflow-hidden">
      {/* Subtle bg glow */}
      <div className="absolute inset-0 bg-gradient-to-b from-space-cadet/0 via-cyan-azure/4 to-space-cadet/0 pointer-events-none" />

      <div className="container mx-auto px-4 relative">
        {/* Section header */}
        <div className="text-center mb-16">
          <span className="inline-block px-3 py-1 rounded-full badge-primary text-xs font-semibold uppercase tracking-wider mb-4 text-cyan-azure">
            Detection Suite
          </span>
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-foreground mb-4">
            Supported{' '}
            <span className="gradient-text">Content Types</span>
          </h2>
          <p className="text-air-sup-blue max-w-2xl mx-auto leading-relaxed">
            Our comprehensive suite of detection tools analyzes various media formats to determine
            authenticity and origin.
          </p>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((f, i) => {
            const accent = accentCycles[i % accentCycles.length];
            return (
              <div
                key={i}
                className="group relative p-6 rounded-2xl glass-card glass-card-hover overflow-hidden"
              >
                {/* Hover gradient overlay */}
                <div className="absolute inset-0 bg-gradient-to-br from-cyan-azure/5 via-transparent to-pink-lavender/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />

                <div className="relative z-10">
                  {/* Icon */}
                  <div className={`w-12 h-12 rounded-xl border flex items-center justify-center mb-4 transition-all duration-300 ${accent}`}>
                    <f.icon className="w-6 h-6" />
                  </div>

                  <h3 className="text-base font-semibold text-foreground mb-2 group-hover:text-pink-lavender transition-colors">
                    {f.title}
                  </h3>
                  <p className="text-sm text-air-sup-blue leading-relaxed">{f.desc}</p>
                </div>

                {/* Bottom accent line on hover */}
                <div className="absolute bottom-0 left-0 h-0.5 w-0 group-hover:w-full bg-gradient-to-r from-cyan-azure to-pink-lavender transition-all duration-500" />
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
