import { FileText, Image as ImageIcon, Video, UserX, Sparkles, Layers, Database, Files } from 'lucide-react';

const features = [
  { title: 'AI Text Detection', icon: FileText, desc: 'Identify text generated by ChatGPT, Claude, Gemini, and other LLMs.' },
  { title: 'AI Image Detection', icon: ImageIcon, desc: 'Detect images created by Midjourney, DALL-E, Stable Diffusion, etc.' },
  { title: 'AI Video Detection', icon: Video, desc: 'Spot fully synthetic AI-generated video content.' },
  { title: 'Deepfake Detection', icon: UserX, desc: 'Identify face-swaps, lip-sync manipulation, and synthetic voices.' },
  { title: 'Image Enhancement Detection', icon: Sparkles, desc: 'Detect AI upscaling, generative fill, and synthetic edits.' },
  { title: 'Video Enhancement Detection', icon: Layers, desc: 'Spot AI frame interpolation and resolution enhancement.' },
  { title: 'Metadata Analysis', icon: Database, desc: 'Extract and analyze hidden EXIF/metadata for manipulation signs.' },
  { title: 'Batch Analysis', icon: Files, desc: 'Scan multiple files or entire documents at once.' },
];

export function Features() {
  return (
    <section className="py-20 bg-background">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold tracking-tight text-white mb-4">Supported Content Types</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Our comprehensive suite of detection tools analyzes various media formats to determine authenticity and origin.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((f, i) => (
            <div 
              key={i} 
              className="group relative p-6 rounded-2xl bg-surface border border-border hover:border-cyan-500/50 transition-all duration-300 overflow-hidden"
            >
              <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
              <div className="relative z-10">
                <div className="w-12 h-12 rounded-lg bg-background border border-border flex items-center justify-center mb-4 group-hover:border-cyan-500/30 transition-colors">
                  <f.icon className="w-6 h-6 text-cyan-400" />
                </div>
                <h3 className="text-lg font-semibold text-foreground mb-2">{f.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
