'use client';
import { useRef } from 'react';
import { motion, useInView, Variants } from 'framer-motion';
import {
  FileText, Image as ImageIcon, Video, UserX, Sparkles, Layers,
  Database, Files, BookOpen,
} from 'lucide-react';

const features = [
  { title: 'AI Text Detection',    icon: FileText,  desc: 'Identify text generated by ChatGPT, Claude, Gemini, and other LLMs with statistical analysis.' },
  { title: 'Plagiarism Detection', icon: BookOpen,  desc: 'Cross-reference content across millions of sources for copied or paraphrased material.' },
  { title: 'AI Image Detection',   icon: ImageIcon, desc: 'Detect images created by Midjourney, DALL-E, Stable Diffusion with pixel-level analysis.' },
  { title: 'AI Video Detection',   icon: Video,     desc: 'Spot fully synthetic AI-generated video content through temporal signal analysis.' },
  { title: 'Deepfake Detection',   icon: UserX,     desc: 'Identify face-swaps, lip-sync manipulation, and synthetic voice overlays.' },
  { title: 'Image Enhancement',    icon: Sparkles,  desc: 'Detect AI upscaling, generative fill, and invisible synthetic edits in photos.' },
  { title: 'Video Enhancement',    icon: Layers,    desc: 'Spot AI frame interpolation and neural resolution enhancement in video.' },
  { title: 'Metadata Analysis',    icon: Database,  desc: 'Extract and analyze hidden EXIF/metadata for manipulation signatures.' },
  { title: 'Batch Analysis',       icon: Files,     desc: 'Scan multiple files or entire documents simultaneously with unified reporting.' },
];

const accents = [
  { bg: 'bg-cyan-azure/12', border: 'border-cyan-azure/25', text: 'text-cyan-azure',       glow: 'rgba(78,122,177,0.3)'    },
  { bg: 'bg-pink-lavender/12', border: 'border-pink-lavender/25', text: 'text-pink-lavender', glow: 'rgba(206,181,212,0.25)'  },
  { bg: 'bg-air-sup-blue/12', border: 'border-air-sup-blue/25', text: 'text-air-sup-blue',   glow: 'rgba(125,159,192,0.3)'   },
  { bg: 'bg-ucla-blue/20', border: 'border-ucla-blue/30', text: 'text-ucla-blue-light',      glow: 'rgba(80,105,141,0.3)'    },
];

const container: Variants = {
  hidden: {},
  show: { transition: { staggerChildren: 0.08 } },
};
const card: Variants = {
  hidden: { opacity: 0, y: 28, scale: 0.96 },
  show:   { opacity: 1, y: 0,  scale: 1,    transition: { duration: 0.5 } },
};

export function Features() {
  const ref    = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-80px' });

  return (
    <section className="py-28 relative overflow-hidden" style={{ background: '#09182e' }}>
      {/* Background grid */}
      <div className="absolute inset-0 bg-grid-pattern bg-grid-fade opacity-60 pointer-events-none" />
      {/* Top gradient fade */}
      <div className="absolute inset-x-0 top-0 h-32 bg-gradient-to-b from-space-cadet-dark to-transparent pointer-events-none" />
      {/* Bottom gradient fade */}
      <div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-[#09182e] to-transparent pointer-events-none" />

      {/* Ambient orb */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[600px] rounded-full pointer-events-none"
        style={{ background: 'radial-gradient(ellipse, rgba(78,122,177,0.07) 0%, transparent 70%)' }} />

      <div className="container mx-auto px-4 relative z-10">
        {/* Section header */}
        <motion.div
          className="text-center mb-18"
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.55 }}
          ref={ref}
        >
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full badge-primary text-xs font-semibold uppercase tracking-widest mb-5">
            <Sparkles className="w-3 h-3 text-cyan-azure" />
            Detection Suite
          </span>
          <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-foreground mb-5 leading-tight">
            Supported{' '}
            <span className="gradient-text">Content Types</span>
          </h2>
          <p className="text-air-sup-blue max-w-2xl mx-auto text-lg leading-relaxed">
            Our comprehensive suite of detection tools analyzes every media format to determine authenticity and origin.
          </p>
        </motion.div>

        {/* Cards grid */}
        <motion.div
          className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 max-w-6xl mx-auto"
          variants={container}
          initial="hidden"
          animate={inView ? 'show' : 'hidden'}
        >
          {features.map((f, i) => {
            const a = accents[i % accents.length];
            return (
              <motion.div
                key={i}
                variants={card}
                className="group bento-card rounded-2xl p-6 cursor-default"
                whileHover={{ y: -6 }}
                transition={{ type: 'spring', stiffness: 300, damping: 20 }}
              >
                {/* Gradient top accent */}
                <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan-azure/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />

                {/* Icon */}
                <div className={`w-12 h-12 rounded-xl border ${a.bg} ${a.border} flex items-center justify-center mb-4 transition-all duration-300 group-hover:scale-110`}
                  style={{ boxShadow: `0 0 0 0 ${a.glow}` }}
                >
                  <f.icon className={`w-6 h-6 ${a.text}`} />
                </div>

                <h3 className="text-base font-semibold text-foreground mb-2 group-hover:text-pink-lavender transition-colors duration-200">
                  {f.title}
                </h3>
                <p className="text-sm text-air-sup-blue leading-relaxed">{f.desc}</p>

                {/* Bottom shimmer bar */}
                <div className="absolute bottom-0 left-0 h-0.5 w-0 group-hover:w-full transition-all duration-500 ease-out"
                  style={{ background: `linear-gradient(90deg, #4E7AB1, #CEB5D4)` }} />
              </motion.div>
            );
          })}
        </motion.div>
      </div>
    </section>
  );
}
